### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by ferhado** [vilien/base64-utf8#2]
When I try to encode and decode an Arabic test, I become the error 'base64 malformed!'
**Example**:

```
var str = "فرهادو";
var encodeString = base64.encode(str); // 编码
var decodeString = base64.decode(encodeString); // 解码

console.log(encodeString);
console.log(decodeString);
```

**Comment by vilien** [comment]
It's a bug. New version has been released for this [v1.0.0](https://github.com/vilien/base64-utf8/releases/tag/v1.0.0)
